# Generated by Django 3.1.7 on 2021-04-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.CharField(db_column='RoomID', max_length=5, primary_key=True, serialize=False)),
                ('floor', models.IntegerField(db_column='Floor')),
                ('max_occupancy', models.IntegerField(db_column='Max_Occupancy')),
            ],
            options={
                'db_table': 'Room',
                'managed': False,
            },
        ),
    ]
