# Generated by Django 3.1.7 on 2021-04-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('max_occupancy', models.IntegerField()),
            ],
        ),
    ]
